aai-institute/nnbench

docs/quickstart.md
Added a usage example to `README.md`.
=> Add usage example to README.md

src/nnbench/core.py, src/nnbench/runner.py, src/nnbench/types.py
Some additions and bug fixes that were necessary to get the MNIST example to work.
=> Emergency fixes in preparation for the MNIST example

.gitignore, docs/index.md, docs/tutorials/index.md, docs/tutorials/mnist.md, examples/mnist/benchmarks.py, examples/mnist/mnist.py, mkdocs.yml, pyproject.toml
This is the first larger neural network pipeline example, run on MNIST.
It showcases how easy it is to insert benchmarks into an existing ML pipeline by just defining a runner and structuring benchmarks into a file.
=> Add MNIST example

docs/guides/benchmarks.md
Small formatting error fix that slipped through https://github.com/aai-institute/nnbench/pull/36
=> Add missing triple quotes to start code block

src/nnbench/core.py
Switches out the generated name for a custom name, with the default staying the same as before. The default (function name plus underscore- joined list of keyword arguments) was refactored into a module-private name generator.
Closes #40.
=> Add namegen argument to `@nnbench.{parametrize,product}`

docs/guides/runners.md, mkdocs.yml
Closes https://github.com/aai-institute/nnbench/issues/38
=> Add benchmark runners user guide

pyproject.toml
=> Fix dev status classifier

src/nnbench/context.py, src/nnbench/reporter/base.py, src/nnbench/reporter/duckdb_sql.py, src/nnbench/reporter/file.py, src/nnbench/reporter/util.py, src/nnbench/runner.py, src/nnbench/types.py, tests/test_context.py, tests/test_runner.py
=> Add BenchmarkContext Class

src/nnbench/reporter/file.py
This behavior was too unexpected - the user should get out exactly the file they put in.
Also, there was a chance that the driver ended up as None even after the extension split, so we throw in that case.
=> Revert file extension coercion, add raise statement for missing driver

examples/prefect/pyproject.toml, examples/streamlit/pyproject.toml
=> Switch author and maintainer description in example .toml's

docs/guides/artifacts.md, mkdocs.yml
=> Add Artifacts guide

README.md
=> Add nnbench video to readme

src/nnbench/cli.py
Now we have the subcommands as an argument group, without the "positional" header. The metavar="" bit is hacky, but to my knowledge no better solution currently exists.
Similarly, document boolean options (i.e. --x, --no-x) on the commandline compactly as --[no-]x.
=> Inline boolean option pairs, change subcommand section

README.md
Also adjust output to reflect changes in our console reporter.
=> Fix README lightning demo example

examples/huggingface/runner.py, examples/mnist/mnist.py, src/nnbench/runner.py
This was a serious oversight, which should have been caught by tests.
=> Update code examples, fix parameter hydration bug

src/nnbench/context.py, tests/test_context.py
Puts some unit tests for expected values in provided info, and some data sanity checks where applicable.
=> Add test coverage for `nnbench.context`

.github/workflows/lint-and-test.yaml, .github/workflows/release.yaml, CONTRIBUTING.md, pyproject.toml, uv.lock
Also, update the contribution guide to the uv dev workflow with dependency groups.
=> packaging: Switch to PEP735 dependency groups

.pre-commit-config.yaml, src/nnbench/core.py, src/nnbench/runner.py, src/nnbench/util.py, tests/test_utils.py
=> maint: Drop some dead code, update deps

tests/cli/__init__.py, tests/cli/benchmarks/a.py, tests/cli/benchmarks/b.py, tests/cli/test_parallel_exec.py
Fixes a botched elapsed time calculation, and improves the import situation regarding the time gate.
=> tests: Fix elapsed time calculation, use single delay import

docs/cli/cli.md, docs/cli/fixtures.md, docs/cli/pyproject.md, docs/guides/benchmarks.md, docs/quickstart.md, src/nnbench/cli.py
Fixes a few outdated guides, and improves the CLI reference by introducing some metavars and descriptions.
=> docs: Improve CLI reference and configuration guide

src/nnbench/reporter/__init__.py, src/nnbench/reporter/file.py, src/nnbench/reporter/service.py, src/nnbench/reporter/util.py, src/nnbench/types.py, src/nnbench/util.py
Improves import hygiene, and transfers some duplicate code into different util modules.
=> chore: Clean up several imports and definitions

src/nnbench/cli.py, src/nnbench/compare.py
The necessary building blocks are a comparison operator enum containing all comparison operators, and a comparison maker.
=> feat: Add comparison class
