aai-institute/nnbench

pyproject.toml
src/nnbench/__init__.py
src/nnbench/core.py
src/nnbench/reporter.py
src/nnbench/runner.py
src/nnbench/types.py

The interface is not yet stable, since there are no options defined on the class constructor, and the console does not take any arguments yet.
-------------------
**Refactor interfaces to new nnbench.types module**
This module will be advertised as the one containing (most of) the abstractions that the user can/must implement to customize nnbench.

Add `nnbench.reporter` module, first tabular console implementation

---

src/nnbench/types.py

Adds the base interface without supplying a default implementation. After it is checked in, we can think about whether we want to add a base implementation, e.g. via fsspec.
Fixes #1.

Add barebones Artifact abstraction

---

pyproject.toml
src/nnbench/context.py
src/nnbench/runner.py

The resulting context building/collection code is much easier than with tuples, where you have to do lengthy type checks.
The existing context providers have been changed to return length-1 dictionaries.
B101 has been disabled globally, since it is a nuisance and most people do not compile to bytecode, anyway.

Refactor context values to be dicts

---

src/nnbench/core.py
src/nnbench/types.py
tests/testproject/hello.py

This was redundant with the addition of the `runner.run()` params slot, and everything else can be handled directly via default arguments on the function itself.
The parametrization factory was updated to take the resulting partial instead.
------------------------
Properly type and document the core decorators (d9a8d6b67bdf0118fd616b1512beaf025f68a221)
Previously, the decorator typing was suffering since no proper overloads were available for the parentheses vs. no parentheses cases. These are now added.
As a consequence, both varieties for both decorators now result in sensible return types. This also paves the way for an easier implementation of the cartesian product decorator coming up.
As a consequence of the removed params slot, the function in a parametrized benchmark is replaced …

Remove benchmark `params` slot, type core decorators

---

src/nnbench/runner.py
tests/test_argcheck.py
tests/typechecking/untyped_benchmarks.py

Guard match checks of types in function signature and supplied via the `params` kwarg in the `benchmark` decorators `_check` method against untyped function signatures. 
If untyped, we do not check for matching types. We also log a warning to the `stdout` of the `logger` indicating the untyped parameter and function name.

Handle untyped interfaces in `_check`

---

src/nnbench/__init__.py
src/nnbench/core.py

Adds the third core decorator for parametrizing benchmarks, which is the cartesian product of variable collections. It is exposed as `nnbench.product`.
Compared to the "inner product" approach of `nnbench.parametrize`, which consumes an iterable of dictionaries, this decorator consumes a keyworded collection of iterables, which it then binds to the benchmark function. This results in an "outer product" with a number of benchmarks that is equal to the products of the numbers of values in each iterable.
However, since `functools.partial` binds parameters lazily, users do not immediately get feedback on whether they supplied the correct argument names in the iterable variable keyword arguments. This needs to be improved, by either implementing a check inside the decorator or by typing it to …

Add cartesian product decorator for benchmarks

---

src/nnbench/types.py
tests/test_benchmark_cls.py

Add an `Interface` immutable dataclass to the `Benchmark` class that contains the signature information of a function. I.e.: 
- Keys
- Values
- Key - Value Pairs 
- Defaults

Add interface class member to Benchmark class

---

src/nnbench/core.py

Catches parametrization errors early on.
Repro:
```py
import nnbench
@nnbench.parametrize(parameters=({"a": i, "b": i+1} for i in range(3)))
def h(a: int, c: int) -> int:
return a * c
```
gives me 
```py
>           raise TypeError(
f"benchmark {fun.__name__}() got an unexpected keyword argument {diffvar!r}"
)
E           TypeError: benchmark h() got an unexpected keyword argument 'b'
```
on this branch.

Add parameter<->interface check to `nnbench.parametrize`

---

.pre-commit-config.yaml
src/nnbench/runner.py
src/nnbench/types.py
tests/test_argcheck.py
tests/test_benchmark_cls.py

Uses the newly defined benchmark function's interface everywhere.
Fixes a type check which would fail if a variable has two non-identical types in two different benchmarks, but which are compatible (i.e. one is a subtype of the other).
Also fixes an error where a missing default parameter in one benchmark could be overridden by a present one in another benchmark. Now, a missing default value means a missing default in the resulting union interface.

Refactor and improve combined interface check

---

src/nnbench/runner.py
tests/test_benchmarks/tag_selection_benchmark.py
tests/test_runner.py

Remove default argument of BenchmarkRunner.collect() to match defaultless run(). Use tag set intersection for selection.

Fix tag check in collection

---

docs/guides/benchmarks.md
docs/quickstart.md
mkdocs.yml
src/nnbench/core.py
src/nnbench/types.py

- Simplify the example in quickstart.md and align it with the usage example of Benchmarks.
- Add benchmarks example
- Remove overloading of the `@parametrize` and `@product` decorators
- Set `follow_wrapped=False` in `Interface.from_callable`.
Closes #34

Benchmark-user-guide

---

docs/guides/organization.md
mkdocs.yml

Contains the two most important structuring tips - refactoring into a proper directory and semantic grouping - in a user guide document.
Also introduces tags as another layer of organization that allows grouping across different module files.
I based this on the MNIST example #11 to take over those changes for the docs organization, so that needs to go in before this.
Closes #32.

Add benchmark organization guide

---

docs/guides/benchmarks.md
src/nnbench/core.py

The stararg change made the decorator unnecessarily inflexible, as no more plain iterables were allowed.
Adjusts the parametrization example to take a raw tuple instead of unraveled arguments.

Make first argument to `@nnbench.parametrize` a single iterable

---

.pre-commit-config.yaml
pyproject.toml
src/nnbench/core.py

Newer test coverage has reminded us that we check argnames only, not argtypes in parameters of `@nnbench.parametrize` and `@nnbench.product`.
To fix, we grab the expected types from the signature and optionally unwrap them in the appropriate manner if they are generics or union types.

Check type of parametrized argument to avoid mismatch

---

docs/guides/benchmarks.md
docs/guides/customization.md
docs/guides/organization.md
docs/quickstart.md
examples/mnist/mnist.py
mkdocs.yml
src/nnbench/__init__.py
src/nnbench/runner.py
tests/test_argcheck.py
tests/test_runner.py

Covers setup/teardown tasks, context values and providers, and usage of `nnbench.Parameters`.
Introductory examples are given for every aspect to showcase how to get started easily with all of the different aspects.
----------------------------
[Return empty record on collection failure, add BenchmarkRunner to top-level module](https://github.com/aai-institute/nnbench/pull/57/commits/d53fee04d90c01fe004dfb40145a08bd183de61b)
This narrows the runner's return type, which will pay huge dividends for anyone building a custom reporter (which will soon be us).
Also, we now use `nnbench.BenchmarkRunner()` instead of importing from `nnbench.runner`.
Closes #35.

Add customization user guide

---

src/nnbench/core.py
src/nnbench/runner.py

Pads the resulting benchmark JSON document with a bit more information, like start date, elapsed wall time (in nanoseconds), function name, and description.
Also adds `error_occurred` and `error_message` to the JSON doc to stabilize the schema.
Part of #56.
Also makes a type comparison in the parametrize/product interface check compatible with Python < 3.10.

Add more default information to benchmark JSON result

---

README.md
pyproject.toml

Links to the quickstart and examples in the readme, since those are great places to start for new users.
Also changes the pip install instruction to the non-git standard PyPI workflow, because we now have the package pushed.

Final docs changes in preparation for v0.1.0

---

.github/workflows/lint-and-test.yaml
.github/workflows/release.yaml
src/nnbench/context.py
src/nnbench/reporter.py
tests/test_context.py

Instead of sticking the single keys into the top-level context struct, we group them under semantic keys in a lower nested level. This has the benefit that ambiguous keys like "version" or "commit" can be given for multiple context aspects, like Python vs. git vs. ...
Changes the unit tests to operate on the nested structs instead.

Group context structs under top-level semantic keys

---

.pre-commit-config.yaml
docs/guides/benchmarks.md
src/nnbench/runner.py

This eliminates the previous failure case of trying to load a filepath with importlib.
By reordering, we incur more time for the module branch (i.e. if the input is a module name), but this is okay since the checks are cheap.
Fixes #69.

Fix runner collection by checking file path first

---

.pre-commit-config.yaml
src/nnbench/__init__.py
src/nnbench/context.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/base.py
src/nnbench/reporter/duckdb_sql.py
src/nnbench/reporter/file.py
src/nnbench/types.py
tests/test_context.py
tests/test_runner.py

This is a more comprehensive take on context handling before/after a
serialization. Options are now omitting, inlining, or flattening the
context.
Changes the `BenchmarkRecord` class to a dataclass, meaning everything
gets switched over to dotted access.
Turns the file reporter into an IO mixin, which is a good building block
for subsequent uses in other reporters.
----------------------------------------
[Remove reporter registration facility](https://github.com/aai-institute/nnbench/commit/61642861d5d07c253dcdda00d8ad2e83491ade51)
Currently unused, can be reintroduced later if needed.

Improve file drivers, add dict roundtrip methods to `BenchmarkRecord`

---

examples/mnist/mnist.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/base.py
src/nnbench/reporter/duckdb_sql.py
src/nnbench/reporter/file.py

Since the reporter interface is so dynamic (i.e., file I/O needs vastly different arguments than DB I/O), we scrap the read/write APIs from the base class and add it as needed in the child classes.
Adds batched (i.e., multi-record) read/write support and a `FileReporter` class that is just the sum of the `FileIO` and `BenchmarkReporter` interfaces.

Unify batching in file drivers, remove read/write stubs on base reporter

---

src/nnbench/reporter/file.py

~Still work in progress, I'm currently debating which other compressions to add (lzma? xz? ...), and whether to expose the stateful hooks (`get_driver_implementation() | get_compression_algorithm()`) right now instead of letting people roll their own SerDe registry.~
------------------
Works similarly to the file driver lookup, except the compression can
also be None, in which case a normal file descriptor is used.
Canonicalizes the extension of the resulting file regardless of which
file name is used based on driver and compression algorithm. This might
be surprising behavior, but simplifies driver and compression inference
significantly on roundtrips.
Scraps the custom registries in FileIO constructor, because we intend to
expose reg/dereg hooks for the default later on.
Available …

Add compression algorithms facility to file IO 

---

.pre-commit-config.yaml
docs/tutorials/bq.md
examples/bq/benchmarks.py
examples/bq/bq.py
mkdocs.yml
src/nnbench/types.py

In this setup, we show how easy it is to stream records completely
without a reporter by simply ingesting the JSON representations resulting
from `BenchmarkRecord.compact()`.
This might be the way forward for most of our examples in place of a
dedicated reporter.
---------------
[Clean up mypy config to allow dupe filenames in examples/](https://github.com/aai-institute/nnbench/commit/29b38cbc331f57d67a0935e37921edac4898ebd3)
< no message>
[Make contextkeys() an API to handle separator properly](https://github.com/aai-institute/nnbench/commit/a13b7f698dd08e25d035ff22a84b3b784d301b90)
The BQ example revealed that we cannot just store the keys as a property
on our class, since they might not be digestible by a database if certain
illegal characters are used.
For BQ, this was the case with …

Add BQ example to showcase cloud streaming of benchmark records

---

src/nnbench/reporter/file.py

Adds a parquet file driver implemented on top of pyarrow.
Adds a ndjson (newline-delimited JSON) driver that was previously part of the json driver, simplifying the latter and causing written files to have the "ndjson" extension.

Add parquet, ndjson drivers, change registration mechanisms

---

docs/tutorials/duckdb.md
mkdocs.yml

Showcases how to query file-written records obtained from a local benchmark run, both with an inlined context and a flattened one.
Contains a SQL query example with escaped dotted columns, which are necessary as we currently cannot specify the separator to use when writing files to disk using our `FileIO`.

Add duckDB example

---

README.md
docs/tutorials/index.md

Our package is structured well enough that this example is small, so it does not take lots of processing new information to understand.
---------------
For reviewers:
* Does this appropriately convey what we're doing?
* After reading this, could you write the code to add and run a `sum` benchmark without changing the `runner = nnbench.BenchmarkRunner()` and subsequent lines?

Add a lightning demo to the README.md

---

docs/tutorials/artifact_benchmarking.md

These misconfigured paths were the reason why the code snippets were not shown.

Hotfix: Adjust snippet paths

---

README.md
src/nnbench/runner.py
tests/benchmarks/parametrized.py
tests/test_runner.py

Closes #101 
Add the Parameters to a 'BenchmarkRecord' by appending it to the results. Omit the type information from the `Variable` object and only retain variable name and value.

Add Parameters to Benchmarks

---

.github/workflows/lint-and-test.yaml
pyproject.toml
src/nnbench/types.py
tests/conftest.py
tests/test_artifacts.py

Closes #94 
- Should `fsspec` become a first class dependecy such as tabulate? Or do we import it conditionally in the `FilepathArtifactLoader`?

Implement a FSspec based ArtifactLoader

---

docs/tutorials/artifact_benchmarking.md
examples/artifact_benchmarking/src/runner.py
src/nnbench/types.py

It is redundant as we have added the deserialization logic in the `Artifact.value` call.
It was therefore only a somewhat useless wrapper around a list. 
Removed mentions from docs as well.
Closes #108

Remove the `ArtifactCollection` class

---

src/nnbench/types.py

Inline the `_cleanup` function for the `FilePathArtifactLoader`. 
The arguments of `weakref.finalize(obj, func, /, *args, **kwargs)` [should not](https://docs.python.org/3/library/weakref.html#weakref.finalize) own any references to `obj`. Otherwise, the object is never garbage collected.

Inline the `_cleanup` function for the `FilePathArtifactLoader`. 

---

src/nnbench/context.py
src/nnbench/runner.py
tests/test_context.py

Closes #99 
The `.add` and `.update` methods of the `Context` now check for
key collisions. With the `replace=False` `kwarg` the user can cus-
tomize the behaviour. Upon collision a ValueError is raised.
Remove collision logic from `runner.run` method as it is now hand-
led in the `Context.add` method.
The `.add` method is implemented in term of `.update` to stay DRY.
Change some tests as they contained key collisions.
Updated tests test the desired behaviour based upon the `replace`
flag.

Unique keys

---

docs/tutorials/artifact_benchmarking.md
examples/artifact_benchmarking/src/benchmark.py

To use `functools.partial` for `parametrize` (and `product`) it is necessary to call the function returned by `partial`. Other- wise collection does not work.
Add these insights in the guide and example.
Closes #96

`functools.partial`ize the `nnbench.parametrize` decorators.

---

docs/guides/transforms.md
examples/transforms/transforms.py
mkdocs.yml
src/nnbench/io/transforms.py
src/nnbench/types.py

Based on the changes contained in #110 (although mostly if not entirely orthogonal).
The proposed `Transform` class is a thin, possibly stateful class mapping
records to other records.
It is generally assumed to be invertible, which is expressed by the
addition of an `iapply()` method (name pending), which can be used to
(approximately) revert records to their old form IF the given transform
supports it.
The added script showcases both proposals, with a barebones example of
why it is useful: To serialize a given model into a set of digestible,
unique identifiers, and doing the reverse in the inverse method.
This way, even custom model classes can be written to JSON, where they
are (very simply) saved via their chosen transform parametrization.

Add transform proposal

---

src/nnbench/util.py

Fixes a bug that prevents in-file benchmark execution due to a type mismatch when calling runner.run() with __file__ as argument (or just the name).
The reason was that on encountering a file name, the Python module that the file pointed to was imported under its absolute path name regardless of whether it was already present in sys.modules (in this case, it was, because it is also __main__).
Adds a check in `import_file_as_module` whether a module already exists in sys.modules for the given file name, in which case that module is returned.
Fixes #115.

Check loaded module names before importing a new one from a file

---

docs/_scripts/gen_api_ref_pages.py
pyproject.toml
requirements-docs.txt

This is the same change set for the docpage generation script, see https://github.com/aai-institute/lakefs-spec/pull/273.

Rollforward of lakefs-spec doc changes

---

src/nnbench/core.py
src/nnbench/runner.py
src/nnbench/types/__init__.py
src/nnbench/types/types.py

Closes #125 
Trailing ToDos (actual work with the `State` Object in setup and teardown tasks will be addressed in the PR for #126  .

State injection into setup and teardown

---

.gitignore
.pre-commit-config.yaml
requirements-dev.txt
requirements-docs.txt
src/nnbench/types/types.py

This is useful to have when profiling memory usage on nnbench.

Update dev requirements, add Memray artifacts to gitignore

---

docs/guides/memoization.md
src/nnbench/runner.py
src/nnbench/types/memo.py

Two steps:
1) Add back the compressed parameter representation to nnbench's runner. There is unfortunately no other way around this, since we have no way out after the record gets persisted.
2) Implement another memo cache API, getting a memo ID (or None) for a memoized value. This is needed for eviction in teardown tasks, which are passed the memo values and not the memos themselves.
The documentation on memos was amended to showcase a dealloc in a teardown task.
The repro on a ~1GB array:
```python
import gc
import logging
import numpy as np
import nnbench
from nnbench.types import Memo, cached_memo
from nnbench.types.memo import evict_memo, get_memo_by_value, memo_cache_size
logging.basicConfig()
logger = logging.getLogger("nnbench")
logger.setLevel(logging.DEBUG)
class …
```

Implement memo garbage collection

---

src/nnbench/runner.py

as the default can be an array. If that is the case the previous implementation fails in the if clause as the truth value of an array is ambiguous.
Previously the following would fail: 
```python
@nnbench.parametrize(({"a": np.zeros((10**5,))},))
def matsquare(a):
return a @ a
```

(fix) Change default == value to is

---

src/nnbench/context.py
tests/test_context.py

as the context information might not be available on all devices, e.g. in our GitHub CI VM the CPU frequency.
Wrap setting of dict entry in a try, except blog that throws warnings when a value cannot be obtained.
This is to address the CI failure described in #145 and very much a suggestion that we can discuss. 
In any case, I think a failure of getting context info should not break the test execution in case they take some time.
As a data scientist using nnbench, I would want our suite to run through so i can react to failures. However, I definitely want information about missing values such that i can implement fixes to these in case they are crucial.

Safe setting of CPU Info

---

pyproject.toml
src/nnbench/__init__.py
src/nnbench/__main__.py
src/nnbench/cli.py

Supports `nnbench <benchmark> <options>` as well as `python -m nnbench <benchmark> <options>`.
Like pytest, we give the option to omit the target location, in which case it becomes a directory named "benchmarks".
Supports a very rudimentary context building from switches method, and tag filtering via switch.

Add CLI entrypoints for module and program invocation

---

.github/workflows/lint-and-test.yaml
.pre-commit-config.yaml
uv.lock

Since it's been released, we should start testing it as well.
---------
Same problem as in lakefs-spec, we rely on pyarrow, which does not have 3.13 wheels yet.

Add Python 3.13 tests to CI

---

pyproject.toml
src/nnbench/__init__.py
uv.lock

setuptools_scm has a few drawbacks to version management by hand, such as inflexibility for releasing off-tag, and missing info on shallow checkouts.
As such, revert back to a static version number, with tagged commits as version bumps.

Remove setuptools_scm in favor of explicit version management

---

src/nnbench/reporter/file.py
src/nnbench/types/benchmark.py
tests/test_fileio.py

The context struct can be passed directly in all options we currently consider, so we don't give the option anymore.

Remove context processing options

---

docs/tutorials/duckdb.md
src/nnbench/cli.py
src/nnbench/reporter/file.py
src/nnbench/runner.py
tests/test_fileio.py

~This will be used to wire up an output to either the console or any supported file format once the interface is canonicalized.~
-----------------
This PR ended up containing a bunch of changes related to file outputs and command line usage of nnbench. Main changes are:
1) Users can now save benchmark results to files via `nnbench benchmarks.py -o record.json` (or any other supported file format).
2) Users can **also** write files directly to remote storage implementations, provided there is an fsspec implementation for it: `nnbench benchmarks.py -o s3://my-bucket/record.json` (requires fsspec and the file system implementation of choice be installed).
3) Context values are now wired into the record when passed on the command line, i.e. `nnbench benchmarks.py --context=foo=bar` creates a …

Remove compression, support file reporting and context passing on the command line

---

pyproject.toml
src/nnbench/cli.py
src/nnbench/compare.py
uv.lock

Works using metric (benchmark) names as columns, and records as lines. Alternatively, we could support metrics as rows and record IDs as columns in the future.
Contains logic to add parameter values and context values to the table as columns, also directly on the command line. In the future, we could make a comparison class that can be subclassed to avoid option clutter on the command line for customizing the rich table display.

Add `nnbench compare` subcommand, comparison function

---

src/nnbench/runner.py
src/nnbench/types/benchmark.py
tests/test_fileio.py

This enables the user to specify names for their experiments, and gives a good primary key for database dumps of benchmarks (upcoming).
Closes #169.

Add run name to benchmark record

---

pyproject.toml
src/nnbench/cli.py
src/nnbench/config.py
src/nnbench/context.py
src/nnbench/reporter/console.py
src/nnbench/runner.py
uv.lock

Contains version-aware stubs for importing a standard-library TOML parser for Python 3.10+ (our support matrix).
Next, we will parse out `tool.nnbench` fields, validate their structure, and instantiate different types of command classes from there.
Working towards #159.

Add TOML config parsing stub

---

.pre-commit-config.yaml
src/nnbench/__init__.py
src/nnbench/cli.py
src/nnbench/compare.py
src/nnbench/config.py
src/nnbench/context.py
src/nnbench/fixtures.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/console.py
src/nnbench/reporter/file.py
src/nnbench/runner.py
src/nnbench/types/__init__.py
src/nnbench/types/benchmark.py
src/nnbench/types/interface.py
src/nnbench/types/memo.py
src/nnbench/util.py

Also fix a bug in `nnbench.util.flatten()`, which did not use the correct key on a dictionary update.
Working towards #177.

Add API docs for all direct `nnbench` submodules

---

src/nnbench/cli.py
src/nnbench/config.py

This ensures that if the configured classpath is a function, the user is allowed to not pass an `arguments` field, and omit the inline arguments table from the TOML table.

Make arguments optional on `ContextProviderDef`

---

docs/cli/fixtures.md
mkdocs.yml

Covers all implemented aspects on fixtures, their nested directory discovery, and limitations compared to pytest.

Add fixture usage guide document

---

src/nnbench/runner.py

This ensures better flexibility when needing to override the builtin parameter representation facility.
Additionally, guard against interface mismatches when calling `val.to_json()`, which happened in the Huggingface example. In that case, fall back (also in general) to the value of repr(val).

Refactor jsonifier to be taken as an argument to `BenchmarkRunner.run()`

---

src/nnbench/config.py
tests/test_config.py

Covers basic TOML keys, TOML with foreign keys (no logs are produced yet). and pyproject.toml not found (produces a debug log).

Add tests for `nnbench.config`

---

docs/guides/index.md
docs/quickstart.md
mkdocs.yml

The guide has been written in the meantime.

Fix dead nnbench logo link, remove stale TODO from quickstart

---

docs/guides/customization.md
docs/guides/organization.md
docs/guides/runners.md
docs/tutorials/duckdb.md
docs/tutorials/huggingface.md
docs/tutorials/mnist.md
examples/bq/bq.py
examples/huggingface/runner.py
examples/mnist/mnist.py
examples/prefect/src/runner.py
src/nnbench/__init__.py
src/nnbench/cli.py
src/nnbench/context.py
src/nnbench/runner.py
tests/test_runner.py

The class had little to no useful state, anyways, and these two standalone APIs play
way better with threading and concurrency, so we opt for functional APIs instead of
a monolithic class.
This is effectively an idiom change - before, we were instantiating as
`runner = nnbench.BenchmarkRunner`, whereas now, we go the extra mile to
collect in the open (`benchmarks = nnbench.collect(path, tags=...)`), and
then pass them as the first argument to the "new" `nnbench.run()` API, which
is just the BenchmarkRunner.run() with the path and tags arguments removed.
This also prevents erroneous caching and persistence of large params to an extent,
since the benchmark list is made explicit.
We had relatively few consumers, namely the main module and the CLI, so the migration was
not as hard as …

Replace `nnbench.BenchmarkRunner` with modular `nnbench.collect()` and `nnbench.run()` APIs

---

.github/workflows/lint-and-test.yaml
.github/workflows/release.yaml

Newest `setup-uv` has the means to install a Python version by argument, and automatically creates a venv to install / sync in.
Also, caching is now enabled by default, which should save some time and bandwidth.

Bump `setup-uv` to v5, change Python install flow

---

.github/actions/mike-docs/action.yaml
.github/workflows/lint-and-test.yaml
.github/workflows/release.yaml
.pre-commit-config.yaml

Mirrors the same change in https://github.com/aai-institute/lakefs-spec/pull/311.
Findings include the frequently missing `persist-credentials`, and a template injection hint for our mike action, which appears three times (?).

Add zizmor pre-commit hook

---

.github/workflows/lint-and-test.yaml
.github/workflows/release.yaml

Otherwise, no commit can be pushed by mike.
The optimal solution would be to persist only in the event of "push on main" (hence why I merged the initial zizmor PR, the CI was green because no push occurred), but that's outside the scope of zizmor for now, which will flag anything but "true".

Persist credentials for mike push jobs

---

.pre-commit-config.yaml
src/nnbench/fixtures.py
src/nnbench/runner.py
uv.lock

We only check against inspect.Parameter.empty, which is a singleton, so `==` and `is` produce the same result.
This is necessary for being able to pass ndarrays as arguments.

Use `is` instead of `==/!=` operators in argument checks

---

pyproject.toml
src/nnbench/core.py
src/nnbench/runner.py
src/nnbench/types.py
tests/integration/test_benchmark_family_memory_consumption.py
tests/test_core.py

Designed to consume the arguments of `parametrize`/`product`, and yield benchmarks lazily.
Params needs to support lazy iterables as well, to not fall into the eager materialization + memory blowup trap.
--------------------------
Testing should contain these scenarios at minimum:
1) Confirm that `BenchmarkFamily`s are being picked up by `nnbench.collect()`, similarly to existing collect checks.
2) Add a test that would fail with an eager iterable (e.g. `list[Benchmark` like it is now), asserting memory consumption stays low e.g. with memray.
Proposal for 2):
Add a benchmark `matmul(a: np.ndarray, b: np.ndarray)` with two arrays $a, b \in \mathbb{R}^{N \times N}$, parametrize over one of them (five `np.random.randn`s should suffice), assert that memory consumption stays near `3 * N^2 * …

Add `BenchmarkFamily` iterable

---

.github/workflows/lint-and-test.yaml
.github/workflows/release.yaml
.pre-commit-config.yaml
docs/guides/benchmarks.md
docs/guides/customization.md
docs/guides/organization.md
docs/quickstart.md

These were leftover from the (semi-)recent change to functional APIs.
-----------
This accommodates new audits of zizmor targeted at excessive / unset workflow permissions.

docs: Remove stale `BenchmarkRunner` references, update hooks

---

.github/workflows/lint-and-test.yaml

This allows docs deployments on `main` pushes.

docs: Allow writes for mike action

---

src/nnbench/cli.py
src/nnbench/context.py
src/nnbench/runner.py
tests/cli/benchmarks/a.py
tests/cli/benchmarks/b.py
tests/cli/conf.py
tests/cli/test_parallel_exec.py

Usage: `nnbench run <benchmarks> -jN`.
Similar to make, but using process parallelism. The default is to not use multiple processes. What's left to decide is whether to require joblib as a hard dependency for parallelism, to simplify the control flow in the CLI.

feat(cli): Add `-j` option for running benchmarks in parallel

---

src/nnbench/cli.py
src/nnbench/runner.py
src/nnbench/util.py

Previously, when inputting a directory for benchmarking, only benchmarks at that directory level were collected because of the use of `Path.iterdir()`.
However, if we want to support arbitrary depth in a benchmark directory layout, we need to use depth traversal, which is facilitated either by os.walk() or, for 3.12 and newer, Path.walk().
Changes both callsites (CLI+multiprocessing and `nnbench.collect()`) to the new `all_python_files()` API.

fix: Use walk() to traverse more than one directory in benchmark collection

---

src/nnbench/io.py

The goal here is to remove the file reporter, which was a mostly useless stateless shim around the underlying IO implementation, and replace it with a more sound OOP-inspired concept of benchmark record IO (read/write).
-----------------
So far, using a protocol for these IO flavors works okay, and captures the nuances that we have (e.g., you can only open parquet files in binary mode). Still some quirks to iron out, but that's to be expected.
Further steps:

refactor: Renew file IO facilities

---

src/nnbench/cli.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/file.py
src/nnbench/reporter/service.py
src/nnbench/util.py
tests/test_fileio.py

Introduces a `BenchmarkServiceIO` protocol, establishing an interface for streaming JSON results to web services like MLflow, Grafana, WandB, ...
Also introduces multiple dispatch of IO based on the value of `outfile`, i.e. the value of the `-o` switch.
The introduced taxonomy is stdout | file | database | service, and loads a different IO class depending on the detected type of IO requested.
For files, inferring the IO type is a bit harder, since local files are usually given without a leading protocol. For this case, we look at the file extension as well.
Every other IO is detected by the leading protocol of the given URI, so `mlflow://experiment/run/subrun` leads to the MLflow IO being requested.
-------------------------
Usage (create two files, `example.py` and `conf.py`, with the …

Add MLFlowIO to enable MLflow logging of benchmark results

---

README.md
docs/guides/benchmarks.md
docs/quickstart.md
examples/huggingface/runner.py
examples/mnist/mnist.py
src/nnbench/__init__.py
src/nnbench/cli.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/console.py
src/nnbench/reporter/file.py

This lets us skip all the unnecessary enum / type switching.
Also refactors the reporter portion to be a proper submodule without it being imported into the top-level. All docs examples are restructured accordingly.

CLI: Restructure dispatch to be based on URI protocol

---

src/nnbench/cli.py

This is purely for convenience of CLI users.
Usage: `nnbench run benchmarks.py -n my-run-1234`.

cli: Add -n switch to configure run name on command line

---

docs/cli/pyproject.md
src/nnbench/cli.py
src/nnbench/config.py
src/nnbench/runner.py
src/nnbench/util.py

This makes for an easier experience when adding a registered context provider on the command line.
Also refactors some utilities away from the implementation files.

cli: Allow provider names to be passed without "provider" key

---

docs/cli/cli.md
src/nnbench/reporter/service.py
src/nnbench/runner.py

The previous format as a datestring was opinionated and inflexible, and led to some quirks with mlflow reporting. Now, we just log the (integer) timestamp when a run was started, which can then be processed by whichever tool is processing the record.

refactor: Change date key and value type for benchmark timestamp

---

src/nnbench/cli.py
src/nnbench/context.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/file.py
src/nnbench/reporter/service.py
tests/test_runner.py

The query field in `IO.read()` allows us to send data queries to database-like IO interfaces, such as that of most experiment trackers and databases themselves.
The URI support was taken over verbatim from the already working bit in `nnbench run`.
-------------------
Also removes some copied code from `nnbench.reporter.service`.
I'm wondering if it's not worth stabilizing the Reporter interface again with `query: str | None`, and just ignore the query for anything file/stream-based. Would probably save a lot of headache.

cli: Add query to reporter.read interface, add URI support to compare

---

src/nnbench/compare.py
src/nnbench/reporter/__init__.py
src/nnbench/reporter/console.py
src/nnbench/reporter/file.py
src/nnbench/reporter/mlflow.py
src/nnbench/reporter/sqlite.py
src/nnbench/types.py
tests/test_fileio.py

Responsible for reading and writing results to SQLite databases.
This requires a tweak to `BenchmarkResult.from_records()`, because in principle, an SQLite query result can contain an arbitrary number of runs (and so can files for that matter). Thus, the return type is changed to yield a list of benchmarks.
Usage: nnbench run benchmarks.py -o sqlite://my-database.db.

feat: Add SQLite reporter

---

src/nnbench/compare.py
src/nnbench/reporter/mlflow.py

With a `False` default, val1 & val2 can never produce a non-zero exit code even if all checks were satisfied.
Also, fix the MLflow reporter by obtaining the timestamp from the result instead of the benchmark.

fix: Set success to True by default to make boolean additions correct

---

.pre-commit-config.yaml
uv.lock
zizmor.yml

Contains runs of `uv lock --upgrade --refresh` and `pre-commit autoupdate`, respectively.

pre-commit: Add zizmor config, update dependencies

---

.pre-commit-config.yaml
src/nnbench/cli.py
src/nnbench/compare.py
src/nnbench/reporter/console.py
src/nnbench/reporter/file.py
src/nnbench/reporter/mlflow.py
src/nnbench/reporter/sqlite.py
src/nnbench/runner.py
src/nnbench/types.py
src/nnbench/util.py
tests/test_file_reporter.py
uv.lock

It's more natural to let the user write results in a loop, since CLI invocations will typically produce only a single result.
Also removes a large portion of the legacy file reporter code.

refactor: Revert to single result writing in reporter

---

src/nnbench/reporter/console.py
src/nnbench/reporter/file.py
src/nnbench/reporter/mlflow.py
src/nnbench/reporter/sqlite.py
src/nnbench/types.py

This fixes some fallout of the removal of iterable results from the reporter interface.
It also renames the input/output path argument to "path". Naming them differently for files (where it was "file" or "fp") and databases (where it was "uri") is technically a Liskov violation, if the arguments are not marked as positional only.

fix: Rename output path argument to "path", fix MLflow reporter

---

docs/cli/cli.md
docs/cli/comparisons.md
mkdocs.yml
src/nnbench/cli.py
src/nnbench/compare.py

Mentions the JSON file and schema, and gives an example with per-metric comparison functions.
------------------
[refactor: Add back context value displays to comparison](https://github.com/aai-institute/nnbench/commit/1a2928f22afe0d9ae593be7489c715833df603ce)
No parameter displays currently, since we are not extracting the parameters per result.

docs: Add dedicated doc on comparisons

---

docs/cli/cli.md
docs/cli/comparisons.md
src/nnbench/cli.py
src/nnbench/compare.py

It's not well defined anymore, since on the command line, different benchmarks can take different values for the same argument name.

cli: Remove -P parameter display option for nnbench compare
